name: CI & Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (Jest)
        run: npm run test

      - name: Start development server
        run: npm run dev &
        env:
          CI: true

      - name: Wait for server to be ready
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:5173 > /dev/null; do sleep 2; done'
          echo "Server is ready!"

      - name: Run E2E tests (Cypress)
        run: |
          npx cypress run --config-file cypress.config.cjs --browser chrome --headless
        env:
          CI: true
          DISPLAY: :99

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        if: success()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"ref": "main", "payload": {"deployment": {"environment": "production"}}}' \
            https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_DEPLOY_HOOK }}
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
